{{- if .Values.gateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vfx.fullname" . }}-gateway
  labels:
    {{- include "vfx.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
    - name: http
      port: {{ .Values.gateway.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "vfx.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: gateway
{{- end }}
