// atlas configuration for vfx.
//
// The declarative schema lives in schema/db/schema.sql. Migrations are
// generated by diffing that file against the previously-applied migration
// history under schema/db/migrations/. A throwaway PostgreSQL container
// (atlas's `dev` URL) is used to validate every diff before it is written.

env "local" {
  src = "file://schema/db/schema.sql"
  url = getenv("DATABASE_URL")
  dev = "docker://postgres/16/dev?search_path=public"

  migration {
    dir = "file://schema/db/migrations"
  }

  format {
    migrate {
      diff = "{{ sql . \"  \" }}"
    }
  }
}
